baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Twentyfour-Hugo site"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[params]
	description = "Twentyfour Cups and Cakes"

[[menu.main]]
	name = "Photography"
	url = "/photography"
	weight = 1
[[menu.main]]
	name = "About"
	url = "/about"
	weight = 2
[[menu.main]]
	name = "Privacy"
	url = "/privacy"
	weight = 3	
[[menu.main]]
	name = "Contact"
	url = "/contact"
	weight = 4